version: '3.8'

services:

  # databse section
  sample.basketdb:
    image: redis:alpine
    container_name: sample.basketdb
    restart: always
    ports:
      - "6379:6379"

  #productdb: mysql
  productdb:
    image: mysql:8.0.29
    container_name: productdb
    environment:
      MYSQL_ROOT_PASSWORD: "Passw0rd!"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  # end database

  # infrastructure section
  sample.basket.api:
    image: ${DOCKER_REGISTRY-}sample-basket-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Basket.Api/Dockerfile
    container_name: sample.basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - sample.basketdb
    ports:
      - "6200:80"
    restart: always

# end infrastructure 


# network 
networks:
  default:
    name: microservice_sample
    driver: bridge

# end network


#volumes section
volumes:
  mysql_data:
    name: mysql_data
